public enum AnimationList.NAME // TypeDefIndex: 6315
{
	// Fields
	public int value__; // 0x0
	public const AnimationList.NAME attack_a = 0;
	public const AnimationList.NAME attack_b = 1;
	public const AnimationList.NAME attack_q = 2;
	public const AnimationList.NAME attack_gen = 3;
	public const AnimationList.NAME damage_01 = 4;
	public const AnimationList.NAME spell = 5;
	public const AnimationList.NAME step_back = 6;
	public const AnimationList.NAME step_front = 7;
	public const AnimationList.NAME treasure_arms = 8;
	public const AnimationList.NAME wait = 9;
	public const AnimationList.NAME death_01 = 10;
	public const AnimationList.NAME attack_ex = 11;
	public const AnimationList.NAME attack_a02 = 12;
	public const AnimationList.NAME attack_b02 = 13;
	public const AnimationList.NAME attack_q02 = 14;
	public const AnimationList.NAME attack_gen02 = 15;
	public const AnimationList.NAME attack_ex02 = 16;
	public const AnimationList.NAME attack_a03 = 17;
	public const AnimationList.NAME attack_b03 = 18;
	public const AnimationList.NAME attack_q03 = 19;
	public const AnimationList.NAME attack_gen03 = 20;
	public const AnimationList.NAME attack_ex03 = 21;
	public const AnimationList.NAME spell02 = 22;
	public const AnimationList.NAME spell03 = 23;
	public const AnimationList.NAME step_back02 = 24;
	public const AnimationList.NAME step_front02 = 25;
	public const AnimationList.NAME attack_a04 = 26;
	public const AnimationList.NAME attack_b04 = 27;
	public const AnimationList.NAME attack_q04 = 28;
	public const AnimationList.NAME attack_gen04 = 29;
	public const AnimationList.NAME attack_ex04 = 30;
	public const AnimationList.NAME damage_02 = 31;
	public const AnimationList.NAME spell_loop = 32;
	public const AnimationList.NAME treasureArms1_a = 33;
	public const AnimationList.NAME treasureArms2_a = 34;
	public const AnimationList.NAME treasureArms3_a = 35;
	public const AnimationList.NAME treasureArms4_a = 36;
	public const AnimationList.NAME treasureArms5_a = 37;
	public const AnimationList.NAME wait02 = 38;
	public const AnimationList.NAME wait03 = 39;
	public const AnimationList.NAME attack_a05 = 40;
	public const AnimationList.NAME attack_b05 = 41;
	public const AnimationList.NAME attack_q05 = 42;
	public const AnimationList.NAME attack_gen05 = 43;
	public const AnimationList.NAME attack_ex05 = 44;
	public const AnimationList.NAME spell04 = 45;
	public const AnimationList.NAME spell05 = 46;
	public const AnimationList.NAME sleep_wait01 = 47;
	public const AnimationList.NAME counter_wait01 = 48;
	public const AnimationList.NAME counter_attack01 = 49;
	public const AnimationList.NAME max = 50;
}
