public enum BattleLogicTask.ACTIONTYPE // TypeDefIndex: 9188
{
	// Fields
	public int value__; // 0x0
	public const BattleLogicTask.ACTIONTYPE NONE = 0;
	public const BattleLogicTask.ACTIONTYPE COMMAND_BATTLE = 1;
	public const BattleLogicTask.ACTIONTYPE ADDATTACK = 2;
	public const BattleLogicTask.ACTIONTYPE SKILL = 3;
	public const BattleLogicTask.ACTIONTYPE TREASURE_DEVICE = 4;
	public const BattleLogicTask.ACTIONTYPE OVERWRITE_TREASURE_DEVICE = 5;
	public const BattleLogicTask.ACTIONTYPE BACKSTEP = 6;
	public const BattleLogicTask.ACTIONTYPE SYSTEM = 7;
	public const BattleLogicTask.ACTIONTYPE COMBO_ORDER = 8;
	public const BattleLogicTask.ACTIONTYPE COMMAND_SPELL = 9;
	public const BattleLogicTask.ACTIONTYPE PLAY_MOTION = 10;
	public const BattleLogicTask.ACTIONTYPE ENDTURN_PLAYER = 11;
	public const BattleLogicTask.ACTIONTYPE ENDTURN_ENEMY = 12;
	public const BattleLogicTask.ACTIONTYPE RESURRECTION = 13;
	public const BattleLogicTask.ACTIONTYPE DEAD = 14;
	public const BattleLogicTask.ACTIONTYPE PROC_BUFFDEAD = 15;
	public const BattleLogicTask.ACTIONTYPE ENEMYLOGIC_ENEMYDEAD = 16;
	public const BattleLogicTask.ACTIONTYPE ENEMYLOGIC_PLAYERACTIONEND = 17;
	public const BattleLogicTask.ACTIONTYPE BUFF_ADD_PLAYER = 18;
	public const BattleLogicTask.ACTIONTYPE BUFF_ADD_ENEMY = 19;
	public const BattleLogicTask.ACTIONTYPE STARTTURN_PLAYER = 20;
	public const BattleLogicTask.ACTIONTYPE STARTTURN_ENEMY = 21;
	public const BattleLogicTask.ACTIONTYPE ENEMYLOGIC_STARTTURN = 22;
	public const BattleLogicTask.ACTIONTYPE ENEMYLOGIC_ENDTURN = 23;
	public const BattleLogicTask.ACTIONTYPE FUNCTIONCHECK_ENTRY = 24;
	public const BattleLogicTask.ACTIONTYPE RESERVATION_SKILL = 25;
	public const BattleLogicTask.ACTIONTYPE ENEMYLOGIC_WAVESTART = 26;
	public const BattleLogicTask.ACTIONTYPE CAMERA = 27;
	public const BattleLogicTask.ACTIONTYPE FIELDAI_START_ENEMYTURN = 28;
	public const BattleLogicTask.ACTIONTYPE FIELDAI_END_ENEMYTURN = 29;
	public const BattleLogicTask.ACTIONTYPE FIELDAI_START_PLAYERTURN = 30;
	public const BattleLogicTask.ACTIONTYPE FIELDAI_END_PLAYERTURN = 31;
	public const BattleLogicTask.ACTIONTYPE FIELDAI_START_WAVE = 32;
	public const BattleLogicTask.ACTIONTYPE FIELDAI_START_TURN = 33;
	public const BattleLogicTask.ACTIONTYPE FIELDAI_REACT_DEAD = 34;
	public const BattleLogicTask.ACTIONTYPE BREAK_ON_BATTLE = 35;
	public const BattleLogicTask.ACTIONTYPE CHECK_SHIFTSERVANT = 36;
	public const BattleLogicTask.ACTIONTYPE SHIFT_SERVANT = 37;
	public const BattleLogicTask.ACTIONTYPE WITHDRAW = 38;
	public const BattleLogicTask.ACTIONTYPE SHIFT_SERVANT_AFTER = 39;
	public const BattleLogicTask.ACTIONTYPE CHANGE_APP = 40;
	public const BattleLogicTask.ACTIONTYPE ENEMY_MASTER_CUTIN = 41;
	public const BattleLogicTask.ACTIONTYPE LOAD_IMMEDIATE_ENTRY_SERVANT = 42;
	public const BattleLogicTask.ACTIONTYPE FIELDAI_ENTRY_UNIT = 43;
	public const BattleLogicTask.ACTIONTYPE PLAY_FIELD_MOTION = 44;
	public const BattleLogicTask.ACTIONTYPE NPCAI_START_WAVE = 45;
	public const BattleLogicTask.ACTIONTYPE NPCAI_START_TURN = 46;
	public const BattleLogicTask.ACTIONTYPE NPCAI_ENTRY_UNIT = 47;
	public const BattleLogicTask.ACTIONTYPE NPCAI_REACT_DEAD = 48;
	public const BattleLogicTask.ACTIONTYPE NPCAI_START_PLAYERTURN = 49;
	public const BattleLogicTask.ACTIONTYPE NPCAI_END_PLAYERTURN = 50;
	public const BattleLogicTask.ACTIONTYPE NPCAI_START_ENEMYTURN = 51;
	public const BattleLogicTask.ACTIONTYPE NPCAI_END_ENEMYTURN = 52;
}
