public enum CriAtomExAcf.AisacGraphType // TypeDefIndex: 4006
{
	// Fields
	public int value__; // 0x0
	public const CriAtomExAcf.AisacGraphType none = 0;
	public const CriAtomExAcf.AisacGraphType volume = 1;
	public const CriAtomExAcf.AisacGraphType pitch = 2;
	public const CriAtomExAcf.AisacGraphType bandpassHigh = 3;
	public const CriAtomExAcf.AisacGraphType bandpassLow = 4;
	public const CriAtomExAcf.AisacGraphType biquadFreq = 5;
	public const CriAtomExAcf.AisacGraphType biquadQ = 6;
	public const CriAtomExAcf.AisacGraphType busSend0 = 7;
	public const CriAtomExAcf.AisacGraphType busSend1 = 8;
	public const CriAtomExAcf.AisacGraphType busSend2 = 9;
	public const CriAtomExAcf.AisacGraphType busSend3 = 10;
	public const CriAtomExAcf.AisacGraphType busSend4 = 11;
	public const CriAtomExAcf.AisacGraphType busSend5 = 12;
	public const CriAtomExAcf.AisacGraphType busSend6 = 13;
	public const CriAtomExAcf.AisacGraphType busSend7 = 14;
	public const CriAtomExAcf.AisacGraphType pan3dAngel = 15;
	public const CriAtomExAcf.AisacGraphType pan3dVolume = 16;
	public const CriAtomExAcf.AisacGraphType pan3dInteriorDistance = 17;
	public const CriAtomExAcf.AisacGraphType pan3dCenter = 18;
	public const CriAtomExAcf.AisacGraphType pan3dLfe = 19;
	public const CriAtomExAcf.AisacGraphType aisac0 = 20;
	public const CriAtomExAcf.AisacGraphType aisac1 = 21;
	public const CriAtomExAcf.AisacGraphType aisac2 = 22;
	public const CriAtomExAcf.AisacGraphType aisac3 = 23;
	public const CriAtomExAcf.AisacGraphType aisac4 = 24;
	public const CriAtomExAcf.AisacGraphType aisac5 = 25;
	public const CriAtomExAcf.AisacGraphType aisac6 = 26;
	public const CriAtomExAcf.AisacGraphType aisac7 = 27;
	public const CriAtomExAcf.AisacGraphType aisac8 = 28;
	public const CriAtomExAcf.AisacGraphType aisac9 = 29;
	public const CriAtomExAcf.AisacGraphType aisac10 = 30;
	public const CriAtomExAcf.AisacGraphType aisac11 = 31;
	public const CriAtomExAcf.AisacGraphType aisac12 = 32;
	public const CriAtomExAcf.AisacGraphType aisac13 = 33;
	public const CriAtomExAcf.AisacGraphType aisac14 = 34;
	public const CriAtomExAcf.AisacGraphType aisac15 = 35;
	public const CriAtomExAcf.AisacGraphType priority = 36;
	public const CriAtomExAcf.AisacGraphType preDelayTime = 37;
	public const CriAtomExAcf.AisacGraphType biquadGain = 38;
	public const CriAtomExAcf.AisacGraphType pan3dMixdownCenter = 39;
	public const CriAtomExAcf.AisacGraphType pan3dMixdownLfe = 40;
	public const CriAtomExAcf.AisacGraphType egAttack = 41;
	public const CriAtomExAcf.AisacGraphType egRelease = 42;
	public const CriAtomExAcf.AisacGraphType playbackRatio = 43;
	public const CriAtomExAcf.AisacGraphType drySendL = 44;
	public const CriAtomExAcf.AisacGraphType drySendR = 45;
	public const CriAtomExAcf.AisacGraphType drySendCenter = 46;
	public const CriAtomExAcf.AisacGraphType drySendLfe = 47;
	public const CriAtomExAcf.AisacGraphType drySendSl = 48;
	public const CriAtomExAcf.AisacGraphType drySendSr = 49;
	public const CriAtomExAcf.AisacGraphType drySendEx1 = 50;
	public const CriAtomExAcf.AisacGraphType drySendEx2 = 51;
	public const CriAtomExAcf.AisacGraphType panSpread = 52;
}
