public enum FGOActorAnimation.ANIMATIONNAME // TypeDefIndex: 7761
{
	// Fields
	public int value__; // 0x0
	public const FGOActorAnimation.ANIMATIONNAME NONE = 0;
	public const FGOActorAnimation.ANIMATIONNAME attack_a = 1;
	public const FGOActorAnimation.ANIMATIONNAME attack_b = 2;
	public const FGOActorAnimation.ANIMATIONNAME attack_q = 3;
	public const FGOActorAnimation.ANIMATIONNAME attack_gen = 4;
	public const FGOActorAnimation.ANIMATIONNAME spell = 5;
	public const FGOActorAnimation.ANIMATIONNAME damage_01 = 6;
	public const FGOActorAnimation.ANIMATIONNAME step_front = 7;
	public const FGOActorAnimation.ANIMATIONNAME step_back = 8;
	public const FGOActorAnimation.ANIMATIONNAME wait = 9;
	public const FGOActorAnimation.ANIMATIONNAME treasure_arms = 10;
	public const FGOActorAnimation.ANIMATIONNAME death_01 = 11;
	public const FGOActorAnimation.ANIMATIONNAME attack_ex = 12;
	public const FGOActorAnimation.ANIMATIONNAME attack_a02 = 13;
	public const FGOActorAnimation.ANIMATIONNAME attack_b02 = 14;
	public const FGOActorAnimation.ANIMATIONNAME attack_q02 = 15;
	public const FGOActorAnimation.ANIMATIONNAME attack_gen02 = 16;
	public const FGOActorAnimation.ANIMATIONNAME attack_ex02 = 17;
	public const FGOActorAnimation.ANIMATIONNAME attack_a03 = 18;
	public const FGOActorAnimation.ANIMATIONNAME attack_b03 = 19;
	public const FGOActorAnimation.ANIMATIONNAME attack_q03 = 20;
	public const FGOActorAnimation.ANIMATIONNAME attack_gen03 = 21;
	public const FGOActorAnimation.ANIMATIONNAME attack_ex03 = 22;
	public const FGOActorAnimation.ANIMATIONNAME spell02 = 23;
	public const FGOActorAnimation.ANIMATIONNAME spell03 = 24;
	public const FGOActorAnimation.ANIMATIONNAME step_back02 = 25;
	public const FGOActorAnimation.ANIMATIONNAME step_front02 = 26;
	public const FGOActorAnimation.ANIMATIONNAME attack_a04 = 27;
	public const FGOActorAnimation.ANIMATIONNAME attack_b04 = 28;
	public const FGOActorAnimation.ANIMATIONNAME attack_q04 = 29;
	public const FGOActorAnimation.ANIMATIONNAME attack_gen04 = 30;
	public const FGOActorAnimation.ANIMATIONNAME attack_ex04 = 31;
	public const FGOActorAnimation.ANIMATIONNAME damage_02 = 32;
	public const FGOActorAnimation.ANIMATIONNAME spell_loop = 33;
	public const FGOActorAnimation.ANIMATIONNAME treasureArms1_a = 34;
	public const FGOActorAnimation.ANIMATIONNAME treasureArms2_a = 35;
	public const FGOActorAnimation.ANIMATIONNAME treasureArms3_a = 36;
	public const FGOActorAnimation.ANIMATIONNAME treasureArms4_a = 37;
	public const FGOActorAnimation.ANIMATIONNAME treasureArms5_a = 38;
	public const FGOActorAnimation.ANIMATIONNAME wait02 = 39;
	public const FGOActorAnimation.ANIMATIONNAME wait03 = 40;
	public const FGOActorAnimation.ANIMATIONNAME attack_a05 = 41;
	public const FGOActorAnimation.ANIMATIONNAME attack_b05 = 42;
	public const FGOActorAnimation.ANIMATIONNAME attack_q05 = 43;
	public const FGOActorAnimation.ANIMATIONNAME attack_gen05 = 44;
	public const FGOActorAnimation.ANIMATIONNAME attack_ex05 = 45;
	public const FGOActorAnimation.ANIMATIONNAME sleep_wait01 = 46;
	public const FGOActorAnimation.ANIMATIONNAME spell04 = 47;
	public const FGOActorAnimation.ANIMATIONNAME spell05 = 48;
}
