public enum FGOLogic.PROC // TypeDefIndex: 7498
{
	// Fields
	public int value__; // 0x0
	public const FGOLogic.PROC INIT_QUEST = 0;
	public const FGOLogic.PROC DRAW_COMMAND = 1;
	public const FGOLogic.PROC CHECK_COMBO = 2;
	public const FGOLogic.PROC INIT_BATTLETURN = 3;
	public const FGOLogic.PROC SELECT_TACTICAL = 4;
	public const FGOLogic.PROC END_BATTLETURN = 5;
	public const FGOLogic.PROC CHECK_ENDBATTLE = 6;
	public const FGOLogic.PROC TURN_PROGRSSING = 7;
	public const FGOLogic.PROC CHECK_BATTLEEND = 8;
	public const FGOLogic.PROC TEST_INITBATTLETURN = 9;
	public const FGOLogic.PROC LOAD_N_STAGE = 10;
	public const FGOLogic.PROC ENTRY_SUBMEMBER = 11;
	public const FGOLogic.PROC CHECK_NEXTBATTLE = 12;
	public const FGOLogic.PROC SET_NEXTBATTLE = 13;
	public const FGOLogic.PROC START_BATTLETURN = 14;
	public const FGOLogic.PROC PROC_WIN = 15;
	public const FGOLogic.PROC PROC_LOSE = 16;
	public const FGOLogic.PROC END_BATTLE = 17;
	public const FGOLogic.PROC CONNECT_BATTLEEND = 18;
	public const FGOLogic.PROC SHOW_RESULT = 19;
	public const FGOLogic.PROC LOAD_NEXT = 20;
	public const FGOLogic.PROC START_CONTINUE = 21;
	public const FGOLogic.PROC RECOVERPT = 22;
	public const FGOLogic.PROC START_COMMAND = 23;
	public const FGOLogic.PROC ENTRY_CHECK = 24;
	public const FGOLogic.PROC ENTRY_WAIT = 25;
	public const FGOLogic.PROC LOSE_PERFORMANCE = 26;
	public const FGOLogic.PROC FIELDAI_STARTWAVE = 27;
	public const FGOLogic.PROC BOOSTITEM = 28;
	public const FGOLogic.PROC WAVEBUFF = 29;
	public const FGOLogic.PROC FIRSTENTRY = 30;
	public const FGOLogic.PROC ENEMYAI_WAVE = 31;
	public const FGOLogic.PROC FIELDAI_TURNSTART = 32;
	public const FGOLogic.PROC START_CONTINUE_TURN = 33;
	public const FGOLogic.PROC ENTRY_CHECK_TACTICAL = 34;
	public const FGOLogic.PROC ENTRY_WAIT_TACTICAL = 35;
	public const FGOLogic.PROC RECOVERPT_TACTICAL = 36;
	public const FGOLogic.PROC QUEST_BEHAVIOR = 37;
	public const FGOLogic.PROC GIMMICK = 38;
	public const FGOLogic.PROC STAR_DIRECTION = 39;
	public const FGOLogic.PROC ENTRY_CHECK_EVENT = 40;
	public const FGOLogic.PROC DROP_ITEM_COLLECTION = 41;
	public const FGOLogic.PROC FORCE_DROP_ITEM = 42;
	public const FGOLogic.PROC CHECK_ENDBATTLE_IGNORE_TURN = 43;
	public const FGOLogic.PROC CHECK_REMAIN_BATTLE_END_WAVE = 44;
	public const FGOLogic.PROC BOOST_SKILL = 45;
	public const FGOLogic.PROC ASSIST = 46;
}
