protected enum FriendRootComponent.State // TypeDefIndex: 10136
{
	// Fields
	public int value__; // 0x0
	public const FriendRootComponent.State INIT = 0;
	public const FriendRootComponent.State INIT_TOP = 1;
	public const FriendRootComponent.State INIT_SHOW_FRIEND = 2;
	public const FriendRootComponent.State INIT_SHOW_FRIEND2 = 3;
	public const FriendRootComponent.State INPUT_SHOW_FRIEND = 4;
	public const FriendRootComponent.State QUIT_SHOW_FRIEND = 5;
	public const FriendRootComponent.State QUIT_SHOW_FRIEND2 = 6;
	public const FriendRootComponent.State INIT_SHOW_OFFER = 7;
	public const FriendRootComponent.State INIT_SHOW_OFFER2 = 8;
	public const FriendRootComponent.State INPUT_SHOW_OFFER = 9;
	public const FriendRootComponent.State QUIT_SHOW_OFFER = 10;
	public const FriendRootComponent.State QUIT_SHOW_OFFER2 = 11;
	public const FriendRootComponent.State INIT_SHOW_OFFERED = 12;
	public const FriendRootComponent.State INIT_SHOW_OFFERED2 = 13;
	public const FriendRootComponent.State INPUT_SHOW_OFFERED = 14;
	public const FriendRootComponent.State QUIT_SHOW_OFFERED = 15;
	public const FriendRootComponent.State QUIT_SHOW_OFFERED2 = 16;
	public const FriendRootComponent.State INIT_SHOW_SEARCH = 17;
	public const FriendRootComponent.State INIT_SHOW_SEARCH2 = 18;
	public const FriendRootComponent.State INPUT_SHOW_SEARCH = 19;
	public const FriendRootComponent.State QUIT_SHOW_SEARCH = 20;
	public const FriendRootComponent.State QUIT_SHOW_SEARCH2 = 21;
	public const FriendRootComponent.State INIT_SEARCH_FRIEND = 22;
	public const FriendRootComponent.State INPUT_SEARCH_FRIEND = 23;
	public const FriendRootComponent.State QUIT_SEARCH_FRIEND = 24;
	public const FriendRootComponent.State QUIT_SEARCH_FRIEND2 = 25;
	public const FriendRootComponent.State INIT_FRIEND_OFFER_CONFIRM = 26;
	public const FriendRootComponent.State INPUT_FRIEND_OFFER_CONFIRM = 27;
	public const FriendRootComponent.State QUIT_FRIEND_OFFER_CONFIRM = 28;
	public const FriendRootComponent.State INPUT_FRIEND_OFFER_CONFIRM_MAX_FRIEND = 29;
	public const FriendRootComponent.State INIT_FRIEND_ACCEPT_CONFIRM = 30;
	public const FriendRootComponent.State INPUT_FRIEND_ACCEPT_CONFIRM = 31;
	public const FriendRootComponent.State QUIT_FRIEND_ACCEPT_CONFIRM = 32;
	public const FriendRootComponent.State INIT_FRIEND_REJECT_CONFIRM = 33;
	public const FriendRootComponent.State INPUT_FRIEND_REJECT_CONFIRM = 34;
	public const FriendRootComponent.State QUIT_FRIEND_REJECT_CONFIRM = 35;
	public const FriendRootComponent.State INIT_FRIEND_CANCEL_CONFIRM = 36;
	public const FriendRootComponent.State INPUT_FRIEND_CANCEL_CONFIRM = 37;
	public const FriendRootComponent.State QUIT_FRIEND_CANCEL_CONFIRM = 38;
	public const FriendRootComponent.State INIT_FRIEND_REMOVE_CONFIRM = 39;
	public const FriendRootComponent.State INPUT_FRIEND_REMOVE_CONFIRM = 40;
	public const FriendRootComponent.State QUIT_FRIEND_REMOVE_CONFIRM = 41;
	public const FriendRootComponent.State INPUT_FOLLOW_OFFER_CONFIRM = 42;
	public const FriendRootComponent.State INPUT_FOLLOW_OFFER_CONFIRM_MAX_FOLLOW = 43;
	public const FriendRootComponent.State INPUT_FOLLOW_OFFER_CONFIRM_ALREADY_FOLLOW = 44;
	public const FriendRootComponent.State INPUT_FOLLOW_REMOVE_CONFIRM = 45;
}
