public enum ListViewSort.FilterKind // TypeDefIndex: 8134
{
	// Fields
	public int value__; // 0x0
	public const ListViewSort.FilterKind CLASS_1_13 = 0;
	public const ListViewSort.FilterKind CLASS_2_14 = 1;
	public const ListViewSort.FilterKind CLASS_3_15 = 2;
	public const ListViewSort.FilterKind CLASS_4_16 = 3;
	public const ListViewSort.FilterKind CLASS_5_17 = 4;
	public const ListViewSort.FilterKind CLASS_6_18 = 5;
	public const ListViewSort.FilterKind CLASS_7_19 = 6;
	public const ListViewSort.FilterKind CLASS_ETC = 7;
	public const ListViewSort.FilterKind CLASS_EXP_UP = 8;
	public const ListViewSort.FilterKind CLASS_STATUS_UP = 9;
	public const ListViewSort.FilterKind COLLECTION_NOT_GET = 10;
	public const ListViewSort.FilterKind COLLECTION_FIND = 11;
	public const ListViewSort.FilterKind COLLECTION_GET = 12;
	public const ListViewSort.FilterKind MISSION_CLEAR = 13;
	public const ListViewSort.FilterKind MISSION_PROGRESS = 14;
	public const ListViewSort.FilterKind MISSION_NOSTART = 15;
	public const ListViewSort.FilterKind MISSION_COMPLETE = 16;
	public const ListViewSort.FilterKind MISSION_END = 17;
	public const ListViewSort.FilterKind BONUS_SERVANT = 18;
	public const ListViewSort.FilterKind BONUS_EQUIP = 19;
	public const ListViewSort.FilterKind BONUS_NONE = 20;
	public const ListViewSort.FilterKind LV_NOTMAX = 21;
	public const ListViewSort.FilterKind FIRST_HP = 22;
	public const ListViewSort.FilterKind SECOND_HP = 23;
	public const ListViewSort.FilterKind HPMAX = 24;
	public const ListViewSort.FilterKind FIRST_ATK = 25;
	public const ListViewSort.FilterKind SECOND_ATK = 26;
	public const ListViewSort.FilterKind ATKMAX = 27;
	public const ListViewSort.FilterKind SAME_CLASS = 28;
	public const ListViewSort.FilterKind CAN_SELECT = 29;
	public const ListViewSort.FilterKind EXIST_NOT_OPEN_COSTUME = 30;
	public const ListViewSort.FilterKind NOT_HAVE_RELEASE_ITEM = 31;
	public const ListViewSort.FilterKind COSTUME_NOT_OPEN = 32;
	public const ListViewSort.FilterKind COSTUME_OPEN = 33;
	public const ListViewSort.FilterKind RARITY_COMMON = 34;
	public const ListViewSort.FilterKind RARITY_UNCOMMON = 35;
	public const ListViewSort.FilterKind RARITY_RARE = 36;
	public const ListViewSort.FilterKind RARITY_SRARE = 37;
	public const ListViewSort.FilterKind RARITY_SSRARE = 38;
	public const ListViewSort.FilterKind CHOICE_SELECT = 39;
	public const ListViewSort.FilterKind BONUS_EQUIP_ALL = 40;
	public const ListViewSort.FilterKind BONUS_INDIVIDUAL = 41;
	public const ListViewSort.FilterKind NP_BUSTER = 42;
	public const ListViewSort.FilterKind NP_ARTS = 43;
	public const ListViewSort.FilterKind NP_QUICK = 44;
	public const ListViewSort.FilterKind NP_ATTACK_ENEMY_ONE = 45;
	public const ListViewSort.FilterKind NP_ATTACK_ENEMY_ALL = 46;
	public const ListViewSort.FilterKind NP_SUPPORT = 47;
	public const ListViewSort.FilterKind CLASS_SERVANT = 48;
	public const ListViewSort.FilterKind COLLECTION_ENCOUNT = 49;
	public const ListViewSort.FilterKind SUM = 50;
}
