public enum QuestAfterAction.COMMAND // TypeDefIndex: 11792
{
	// Fields
	public int value__; // 0x0
	public const QuestAfterAction.COMMAND SPOT_HIDE = 100;
	public const QuestAfterAction.COMMAND SPOT_GRAY = 101;
	public const QuestAfterAction.COMMAND SPOT_DISP = 102;
	public const QuestAfterAction.COMMAND SPOT_CHANGE = 103;
	public const QuestAfterAction.COMMAND SPOT_HIDE_QUICK = 110;
	public const QuestAfterAction.COMMAND SPOT_GRAY_QUICK = 111;
	public const QuestAfterAction.COMMAND SPOT_DISP_QUICK = 112;
	public const QuestAfterAction.COMMAND SPOT_CHANGE_QUICK = 113;
	public const QuestAfterAction.COMMAND ROAD_HIDE = 200;
	public const QuestAfterAction.COMMAND ROAD_GRAY = 201;
	public const QuestAfterAction.COMMAND ROAD_DISP = 202;
	public const QuestAfterAction.COMMAND CAM_MV_SPOT = 300;
	public const QuestAfterAction.COMMAND CAM_MV_ROAD = 301;
	public const QuestAfterAction.COMMAND CAM_MV_GIMMICK = 302;
	public const QuestAfterAction.COMMAND CAM_MV_COORD = 303;
	public const QuestAfterAction.COMMAND CAM_ZOOM = 304;
	public const QuestAfterAction.COMMAND CAM_MV_ZOOM_SPOT = 305;
	public const QuestAfterAction.COMMAND CAM_MV_ZOOM_ROAD = 306;
	public const QuestAfterAction.COMMAND CAM_MV_ZOOM_GIMMICK = 307;
	public const QuestAfterAction.COMMAND CAM_MV_ZOOM_COORD = 308;
	public const QuestAfterAction.COMMAND GIMMICK_HIDE = 400;
	public const QuestAfterAction.COMMAND GIMMICK_DISP = 401;
	public const QuestAfterAction.COMMAND GIMMICK_HIDE_QUICK = 402;
	public const QuestAfterAction.COMMAND GIMMICK_DISP_QUICK = 403;
	public const QuestAfterAction.COMMAND GIMMICK_MV_COORD = 404;
	public const QuestAfterAction.COMMAND GIMMICK_DISP_WITH_FADE = 405;
	public const QuestAfterAction.COMMAND GIMMICK_TWEEN_COLOR = 406;
	public const QuestAfterAction.COMMAND GIMMICK_SET_COLOR = 407;
	public const QuestAfterAction.COMMAND GIMMICK_DISP_UPDATE = 408;
	public const QuestAfterAction.COMMAND GIMMICK_DISP_PILE_UP = 409;
	public const QuestAfterAction.COMMAND QUEST_FOCUS = 500;
	public const QuestAfterAction.COMMAND QUEST_UNFOCUS = 501;
	public const QuestAfterAction.COMMAND PLAYER_FOCUS = 510;
	public const QuestAfterAction.COMMAND AFTER_FADE_IN = 520;
	public const QuestAfterAction.COMMAND QUEST_START = 530;
	public const QuestAfterAction.COMMAND MAP_CHANGE = 540;
	public const QuestAfterAction.COMMAND START_MAP_CHANGE = 550;
	public const QuestAfterAction.COMMAND MESSAGE_WINDOW = 600;
	public const QuestAfterAction.COMMAND MESSAGE_WINDOW_MST = 601;
	public const QuestAfterAction.COMMAND MESSAGE_OTHER_WINDOW = 602;
	public const QuestAfterAction.COMMAND MESSAGE_OTHER_WINDOW_MST = 603;
	public const QuestAfterAction.COMMAND MESSAGE_OTHER_WINDOW_BOOST_SUPPORT = 604;
	public const QuestAfterAction.COMMAND EVENT_REWARD = 700;
	public const QuestAfterAction.COMMAND PLAY_VOICE = 800;
	public const QuestAfterAction.COMMAND PLAY_SE = 801;
	public const QuestAfterAction.COMMAND BGM_STOP = 850;
	public const QuestAfterAction.COMMAND BGM_PLAY = 851;
	public const QuestAfterAction.COMMAND WAIT = 900;
}
