public enum TutorialFlag.EventId // TypeDefIndex: 5870
{
	// Fields
	public int value__; // 0x0
	public const TutorialFlag.EventId NULL = -1;
	public const TutorialFlag.EventId TUTORIAL_LABEL_BOOST_ITEM = 0;
	public const TutorialFlag.EventId TUTORIAL_LABEL_HELP = 1;
	public const TutorialFlag.EventId TUTORIAL_LABEL_QUEST = 2;
	public const TutorialFlag.EventId TUTORIAL_LABEL_RESET_QUEST = 3;
	public const TutorialFlag.EventId TUTORIAL_LABEL_REWARD_HELP = 4;
	public const TutorialFlag.EventId TUTORIAL_LABEL_SHOP_HELP = 5;
	public const TutorialFlag.EventId TUTORIAL_LABEL_MISSION_SPOT_OPEN = 6;
	public const TutorialFlag.EventId TUTORIAL_LABEL_MISSION_OPEN_ANOTHER = 7;
	public const TutorialFlag.EventId TUTORIAL_LABEL_BATTLE_START = 8;
	public const TutorialFlag.EventId TUTORIAL_LABEL_BATTLE_TURN = 9;
	public const TutorialFlag.EventId TUTORIAL_LABEL_BATTLE_RESULT = 10;
	public const TutorialFlag.EventId TUTORIAL_LABEL_BATTLE_RESULT_WIN = 11;
	public const TutorialFlag.EventId TUTORIAL_LABEL_BATTLE_RESULT_LOSE = 12;
	public const TutorialFlag.EventId TUTORIAL_LABEL_QUEST2 = 13;
	public const TutorialFlag.EventId TUTORIAL_LABEL_SVTGET = 14;
	public const TutorialFlag.EventId TUTORIAL_LABEL_SHOP = 15;
	public const TutorialFlag.EventId TUTORIAL_LABEL_SUPPORT_SELECT = 16;
	public const TutorialFlag.EventId TUTORIAL_LABEL_EVENT_TAB1_EFFECT = 25;
	public const TutorialFlag.EventId TUTORIAL_LABEL_EVENT_TAB2_EFFECT = 26;
	public const TutorialFlag.EventId TUTORIAL_LABEL_EVENT_TAB3_EFFECT = 27;
	public const TutorialFlag.EventId TUTORIAL_LABEL_BATTLE_WAVE = 28;
	public const TutorialFlag.EventId TUTORIAL_LABEL_COSTUME = 29;
	public const TutorialFlag.EventId TUTORIAL_LABEL_OPEN_SORT_WINDOW = 30;
	public const TutorialFlag.EventId TUTORIAL_LABEL_GACHA = 32;
	public const TutorialFlag.EventId TUTORIAL_LABEL_SVT_COMBINE = 33;
	public const TutorialFlag.EventId TUTORIAL_LABEL_SVT_LIMIT_UP = 34;
	public const TutorialFlag.EventId TUTORIAL_LABEL_SVT_SKILL = 35;
	public const TutorialFlag.EventId TUTORIAL_LABEL_SVT_EQUIP = 36;
	public const TutorialFlag.EventId TUTORIAL_LABEL_SVT_NP = 37;
	public const TutorialFlag.EventId TUTORIAL_LABEL_SVT_LVEXCEED = 38;
	public const TutorialFlag.EventId TUTORIAL_LABEL_OPEN_CHOICE_WINDOW = 39;
	public const TutorialFlag.EventId TUTORIAL_LABEL_OPEN_SMART_CHOICE_WINDOW = 40;
	public const TutorialFlag.EventId TUTORIAL_LABEL_EVENT_TAB4 = 41;
	public const TutorialFlag.EventId TUTORIAL_LABEL_EVENT_TAB4_HELP = 42;
	public const TutorialFlag.EventId TUTORIAL_LABEL_OPEN_QUEST_START = 43;
	public const TutorialFlag.EventId TUTORIAL_LABEL_OPEN_SUPPORT_SETTING = 45;
	public const TutorialFlag.EventId TUTORIAL_LABEL_SVT_EQUIP_FRIENDSHIP_SELECT = 52;
	public const TutorialFlag.EventId SVT_COMBINE_LIMIT_SPECIAL = 53;
	public const TutorialFlag.EventId WAR_BOARD_MAP = 59;
	public const TutorialFlag.EventId WAR_BOARD_SETUP = 60;
	public const TutorialFlag.EventId WAR_BOARD_START = 61;
	public const TutorialFlag.EventId WAR_BOARD_MAP_SETUP = 62;
	public const TutorialFlag.EventId LOGIN_BONUS = 63;
	public const TutorialFlag.EventId OPEN_SPECIFIC_QUEST = 64;
	public const TutorialFlag.EventId QUEST4 = 65;
}
